### ISSUE TITLE
ImportError: No module named 'device'

### ISSUE THREAD

**Issue by Veneth** [girish946/python-R305#5]
Dear Girish,

while running the example program on windows 8.1 I get this error

```
Traceback (most recent call last):
  File "C:\Users\Elcot\Desktop\R305\python-R305-master\examples\store_finger_print.py", line 4, in <module>
    from r305 import R305
  File "C:\Python34\lib\site-packages\r305\__init__.py", line 4, in <module>
    from device import *
ImportError: No module named 'device'
```

even through I connect with R305 by using UART to USB converter

**Comment by ANANTHU-R-NATH** [comment]
which version of python are you using 2/3 ? , i got same issue in 3.5 but works fine in 2.7

**Comment by Veneth** [comment]
Thanks for your very fast reply

**Comment by Kkaranmore** [comment]
same error does you have any solution in python 3 since i have another programe in python 3 needs to run parallel

**Comment by angadskulkarni** [comment]
go to the folder where your site-packages are installed,
look for r305 folder,
inside that, you'll find __init__.py file.
open it- 
and change this line -
from device import *
to -
from .device import *

Just a small dot !
But makes a lot of difference.

Happy coding !
