### ISSUE TITLE
Is this applicable also with R307 fingerprint scanner?

### ISSUE THREAD

**Issue by risurina** [girish946/python-R305#6]

**Comment by girish946** [comment]
Most probably yes. This module should work with R30X series.

**Comment by srinivasaraopusarla** [comment]
how to pass commands to that module with usb.
how to pass them python?
i want to download those templates stored in fingerprint module into my local machine.

**Comment by rajtan** [comment]
If the module supports USB connectionm then there is no issue. You connect to the host and the port is presented as a serial device. However, so far as I know that though these modules mention the USB connectivity, I have not come accross any site or person making a direct USB connection. It seems USB connectivity is optional.

Having said that, if you wish to use it with USB port on the host device / MCU then you may use FTDI based USB to serial converter. Then on the host side, its a USB connection (seen as a serial device to the program) and on the other side, it hax Tx, Rx, Vcc and GND i.e. you cna connect these to FP reader.

**Comment by TehseenHasan** [comment]
@rajtan This is a C# program to communicate with R30x Fingerprint sensor with **USB protocol**... This example downloads scanned fingerprint image from Sensor to our Computer....
https://github.com/TehseenHasan/R305_fingerprint_sensor_usb_interface

Understand the different functions of **SynoAPIEx.dll** file from this example if you want to use this same as pyFingerprint library...

For more details try to read this discussion: https://github.com/dilshan/zfm20-lib/issues/2
